### ISSUE TITLE
Test Image

### ISSUE THREAD

**Issue by purva98** [lychengrex/Image-Denoising-with-Deep-CNNs#2]
Any suggestions on testing it in demo.ipynb for own test-images?

**Comment by lychengrex** [comment]
> Any suggestions on testing it in demo.ipynb for own test-images?

Hi, how I test on other images is demonstrated in [testing-demo.ipynb](https://github.com/lychengr3x/Image-Denoising-with-Deep-CNNs/blob/master/src/testing-demo.ipynb). Hope it helps!

**Comment by purva98** [comment]
Thanks
