### ISSUE TITLE
No check points saved 

### ISSUE THREAD

**Issue by kimile599** [lychengrex/Image-Denoising-with-Deep-CNNs#3]
Hi, 
thank you for sharing the code. It worked well for me on the colab. But when finish training i check the checkpoint, the folder is always empty?

Thanks.

**Comment by kimile599** [comment]
> Hi,
> thank you for sharing the code. It worked well for me on the colab. But when finish training i check the checkpoint, the folder is always empty?
> 
> Thanks.

a quick update，

When i ran it on my own computer, i can see the checkpoint file but when i ran it on colab the issue i imentioned pop up.

Thank you

**Comment by lychengrex** [comment]
> > Hi,
> > thank you for sharing the code. It worked well for me on the colab. But when finish training i check the checkpoint, the folder is always empty?
> > Thanks.
> 
> a quick update，
> 
> When i ran it on my own computer, i can see the checkpoint file but when i ran it on colab the issue i imentioned pop up.
> 
> Thank you

I believe that’s because the root path on colab is at `/content` which is a temporary file system. You need to mount your Google Drive and save checkpoints with full path to the directory on your drive. Please refer to section `Mounting Google Drive locally` at [this tutorial](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=u22w3BFiOveA)

**Comment by kimile599** [comment]
> > > Hi,
> > > thank you for sharing the code. It worked well for me on the colab. But when finish training i check the checkpoint, the folder is always empty?
> > > Thanks.
> > 
> > 
> > a quick update，
> > When i ran it on my own computer, i can see the checkpoint file but when i ran it on colab the issue i imentioned pop up.
> > Thank you
> 
> I believe that’s because the root path on colab is at `/content` which is a temporary file system. You need to mount your Google Drive and save checkpoints with full path to the directory on your drive. Please refer to section `Mounting Google Drive locally` at [this tutorial](https://colab.research.google.com/notebooks/io.ipynb#scrollTo=u22w3BFiOveA)

Thank you for the quick response.
I will try to mount to my gdrive instead of the content folder.
