### ISSUE TITLE
How to get PSNR and loss value from result image at the testing

### ISSUE THREAD

**Issue by albertmanuels** [lychengrex/Image-Denoising-with-Deep-CNNs#6]
Hello,
Can you help me to get and display the psnr and loss value of the result image at the testing? 
Thank you

**Comment by lychengrex** [comment]
> Hello,
> Can you help me to get and display the psnr and loss value of the result image at the testing?
> Thank you

For the PSNR, you can refer to `PSNR` section in [tutorial.ipynb](https://github.com/lychengr3x/Image-Denoising-with-Deep-CNNs/blob/master/src/tutorial.ipynb). For the loss, you can refer to `nntools.evaluate()`([link](https://github.com/lychengr3x/Image-Denoising-with-Deep-CNNs/blob/master/src/nntools.py)).
