### ISSUE TITLE
raise ValueError in training 

### ISSUE THREAD

**Issue by OmarMohammed88** [lychengrex/Image-Denoising-with-Deep-CNNs#7]
"Cannot create this experiment: "
ValueError: Cannot create this experiment: I found a checkpoint conflicting with the current setting.

any solutions?

**Comment by lychengrex** [comment]
> "Cannot create this experiment: "
> ValueError: Cannot create this experiment: I found a checkpoint conflicting with the current setting.
> 
> any solutions?

Please carefully check the configurations of the checkpoint and the current one. There must be something mismatched.
